SELECT	DATAOCORRENCIA AS DATA_OCORRENCIA
		,DB_PRINCIPAL.dbo.fnTrataDescricoes(CONTA) AS CONTA_DESC
		,DB_PRINCIPAL.dbo.fnTrataDescricoes(CATEGORIA) AS CATEGORIA_DESC
		,DB_PRINCIPAL.dbo.fnTrataDescricoes(DESCRICAO) AS LANCAMENTO_DESC
		,DB_PRINCIPAL.dbo.fnTrataValores(VALOR) AS VALOR_PARCELA
		
		,CASE 
				WHEN PATINDEX('%(%/%)',DESCRICAO) > 0 THEN REPLACE(REVERSE(SUBSTRING(REVERSE(SUBSTRING(DESCRICAO, PATINDEX('%(%/%)',DESCRICAO)+1,5)),CHARINDEX('/',REVERSE(SUBSTRING(DESCRICAO, PATINDEX('%(%/%)',DESCRICAO)+1,6))),4)),'/','')
				ELSE 1
		END AS PARCELA_ATUAL
		,CASE 
				WHEN PATINDEX('%(%/%)',DESCRICAO) > 0 THEN RTRIM(LTRIM(REPLACE(SUBSTRING(SUBSTRING(DESCRICAO, PATINDEX('%(%/%)',DESCRICAO),9),CHARINDEX('/',SUBSTRING(DESCRICAO, PATINDEX('%(%/%)',DESCRICAO),9))+1,4),')','')))
				ELSE 1 END AS PARCELA_TOTAL
	,ARQUIVODATACARGA AS DATA_CARGA
FROM	FILE_IMPORTACAO